INSERT INTO line (id, name, color) VALUES (1, '1호선', 'BLUE')
INSERT INTO line (id, name, color) VALUES (2, '2호선', 'GREEN')
INSERT INTO station (id, line_id, name) VALUES (1, 1, '시청역')
INSERT INTO station (id, line_id, name) VALUES (2, 1, '종각역')
INSERT INTO station (id, line_id, name) VALUES (3, 1, '종로3가역')
INSERT INTO station (id, line_id, name) VALUES (4, 2, '교대역')